EVALUATE
	UNION(
		ROW(
			"Table", "Tabla1",
			"Column", "ID Empleado",
			"Count", COUNT('Tabla1'[ID Empleado]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[ID Empleado]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[ID Empleado]),
			"Min", MIN('Tabla1'[ID Empleado]),
			"Max", MAX('Tabla1'[ID Empleado]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla1",
			"Column", "Función",
			"Count", COUNT('Tabla1'[Función]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[Función]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[Función]),
			"Min", MIN('Tabla1'[Función]),
			"Max", MAX('Tabla1'[Función]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla1",
			"Column", "Departamento",
			"Count", COUNT('Tabla1'[Departamento]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[Departamento]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[Departamento]),
			"Min", MIN('Tabla1'[Departamento]),
			"Max", MAX('Tabla1'[Departamento]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla1",
			"Column", "Región",
			"Count", COUNT('Tabla1'[Región]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[Región]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[Región]),
			"Min", MIN('Tabla1'[Región]),
			"Max", MAX('Tabla1'[Región]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla1",
			"Column", "Educación",
			"Count", COUNT('Tabla1'[Educación]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[Educación]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[Educación]),
			"Min", MIN('Tabla1'[Educación]),
			"Max", MAX('Tabla1'[Educación]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla1",
			"Column", "Género",
			"Count", COUNT('Tabla1'[Género]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[Género]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[Género]),
			"Min", MIN('Tabla1'[Género]),
			"Max", MAX('Tabla1'[Género]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla1",
			"Column", "Jornada",
			"Count", COUNT('Tabla1'[Jornada]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[Jornada]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[Jornada]),
			"Min", MIN('Tabla1'[Jornada]),
			"Max", MAX('Tabla1'[Jornada]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla1",
			"Column", "Modalidad",
			"Count", COUNT('Tabla1'[Modalidad]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[Modalidad]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[Modalidad]),
			"Min", MIN('Tabla1'[Modalidad]),
			"Max", MAX('Tabla1'[Modalidad]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla1",
			"Column", "Fecha Contratación",
			"Count", COUNT('Tabla1'[Fecha Contratación]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[Fecha Contratación]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[Fecha Contratación]),
			"Min", MIN('Tabla1'[Fecha Contratación]),
			"Max", MAX('Tabla1'[Fecha Contratación]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", COALESCE(
				COUNTROWS(FILTER(
					'Tabla1',
					'Tabla1'[Fecha Contratación] = 0
				)),
				0
			),
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", DATEDIFF(
				MIN('Tabla1'[Fecha Contratación]),
				MAX('Tabla1'[Fecha Contratación]),
				DAY
			),
			"Range in Months", DATEDIFF(
				MIN('Tabla1'[Fecha Contratación]),
				MAX('Tabla1'[Fecha Contratación]),
				MONTH
			),
			"Range in Years", DATEDIFF(
				MIN('Tabla1'[Fecha Contratación]),
				MAX('Tabla1'[Fecha Contratación]),
				YEAR
			)
		),
		ROW(
			"Table", "Tabla1",
			"Column", "Estatus",
			"Count", COUNT('Tabla1'[Estatus]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[Estatus]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[Estatus]),
			"Min", MIN('Tabla1'[Estatus]),
			"Max", MAX('Tabla1'[Estatus]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla1",
			"Column", "Fecha Baja",
			"Count", COUNT('Tabla1'[Fecha Baja]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla1'[Fecha Baja]),
			"Null Count", COUNTROWS('Tabla1') - COUNT('Tabla1'[Fecha Baja]),
			"Min", MIN('Tabla1'[Fecha Baja]),
			"Max", MAX('Tabla1'[Fecha Baja]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", COALESCE(
				COUNTROWS(FILTER(
					'Tabla1',
					'Tabla1'[Fecha Baja] = 0
				)),
				0
			),
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", DATEDIFF(
				MIN('Tabla1'[Fecha Baja]),
				MAX('Tabla1'[Fecha Baja]),
				DAY
			),
			"Range in Months", DATEDIFF(
				MIN('Tabla1'[Fecha Baja]),
				MAX('Tabla1'[Fecha Baja]),
				MONTH
			),
			"Range in Years", DATEDIFF(
				MIN('Tabla1'[Fecha Baja]),
				MAX('Tabla1'[Fecha Baja]),
				YEAR
			)
		)
	)