EVALUATE
	UNION(
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "ID Empleado",
			"Count", COUNT('Tabla_dataset_RRHH'[ID Empleado]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[ID Empleado]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[ID Empleado]),
			"Min", MIN('Tabla_dataset_RRHH'[ID Empleado]),
			"Max", MAX('Tabla_dataset_RRHH'[ID Empleado]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "Función",
			"Count", COUNT('Tabla_dataset_RRHH'[Función]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[Función]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[Función]),
			"Min", MIN('Tabla_dataset_RRHH'[Función]),
			"Max", MAX('Tabla_dataset_RRHH'[Función]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "Departamento",
			"Count", COUNT('Tabla_dataset_RRHH'[Departamento]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[Departamento]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[Departamento]),
			"Min", MIN('Tabla_dataset_RRHH'[Departamento]),
			"Max", MAX('Tabla_dataset_RRHH'[Departamento]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "Región",
			"Count", COUNT('Tabla_dataset_RRHH'[Región]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[Región]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[Región]),
			"Min", MIN('Tabla_dataset_RRHH'[Región]),
			"Max", MAX('Tabla_dataset_RRHH'[Región]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "Educación",
			"Count", COUNT('Tabla_dataset_RRHH'[Educación]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[Educación]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[Educación]),
			"Min", MIN('Tabla_dataset_RRHH'[Educación]),
			"Max", MAX('Tabla_dataset_RRHH'[Educación]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "Género",
			"Count", COUNT('Tabla_dataset_RRHH'[Género]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[Género]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[Género]),
			"Min", MIN('Tabla_dataset_RRHH'[Género]),
			"Max", MAX('Tabla_dataset_RRHH'[Género]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "Jornada",
			"Count", COUNT('Tabla_dataset_RRHH'[Jornada]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[Jornada]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[Jornada]),
			"Min", MIN('Tabla_dataset_RRHH'[Jornada]),
			"Max", MAX('Tabla_dataset_RRHH'[Jornada]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "Modalidad",
			"Count", COUNT('Tabla_dataset_RRHH'[Modalidad]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[Modalidad]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[Modalidad]),
			"Min", MIN('Tabla_dataset_RRHH'[Modalidad]),
			"Max", MAX('Tabla_dataset_RRHH'[Modalidad]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "Fecha Contratación",
			"Count", COUNT('Tabla_dataset_RRHH'[Fecha Contratación]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[Fecha Contratación]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[Fecha Contratación]),
			"Min", MIN('Tabla_dataset_RRHH'[Fecha Contratación]),
			"Max", MAX('Tabla_dataset_RRHH'[Fecha Contratación]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", COALESCE(
				COUNTROWS(FILTER(
					'Tabla_dataset_RRHH',
					'Tabla_dataset_RRHH'[Fecha Contratación] = 0
				)),
				0
			),
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", DATEDIFF(
				MIN('Tabla_dataset_RRHH'[Fecha Contratación]),
				MAX('Tabla_dataset_RRHH'[Fecha Contratación]),
				DAY
			),
			"Range in Months", DATEDIFF(
				MIN('Tabla_dataset_RRHH'[Fecha Contratación]),
				MAX('Tabla_dataset_RRHH'[Fecha Contratación]),
				MONTH
			),
			"Range in Years", DATEDIFF(
				MIN('Tabla_dataset_RRHH'[Fecha Contratación]),
				MAX('Tabla_dataset_RRHH'[Fecha Contratación]),
				YEAR
			)
		),
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "Estatus",
			"Count", COUNT('Tabla_dataset_RRHH'[Estatus]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[Estatus]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[Estatus]),
			"Min", MIN('Tabla_dataset_RRHH'[Estatus]),
			"Max", MAX('Tabla_dataset_RRHH'[Estatus]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Tabla_dataset_RRHH",
			"Column", "Fecha Baja",
			"Count", COUNT('Tabla_dataset_RRHH'[Fecha Baja]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Tabla_dataset_RRHH'[Fecha Baja]),
			"Null Count", COUNTROWS('Tabla_dataset_RRHH') - COUNT('Tabla_dataset_RRHH'[Fecha Baja]),
			"Min", MIN('Tabla_dataset_RRHH'[Fecha Baja]),
			"Max", MAX('Tabla_dataset_RRHH'[Fecha Baja]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", COALESCE(
				COUNTROWS(FILTER(
					'Tabla_dataset_RRHH',
					'Tabla_dataset_RRHH'[Fecha Baja] = 0
				)),
				0
			),
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", DATEDIFF(
				MIN('Tabla_dataset_RRHH'[Fecha Baja]),
				MAX('Tabla_dataset_RRHH'[Fecha Baja]),
				DAY
			),
			"Range in Months", DATEDIFF(
				MIN('Tabla_dataset_RRHH'[Fecha Baja]),
				MAX('Tabla_dataset_RRHH'[Fecha Baja]),
				MONTH
			),
			"Range in Years", DATEDIFF(
				MIN('Tabla_dataset_RRHH'[Fecha Baja]),
				MAX('Tabla_dataset_RRHH'[Fecha Baja]),
				YEAR
			)
		)
	)